/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpcalculator;

import javax.swing.*;
import java.text.*;

/**
 *Student Number:91023487
 * Name: Mel John del Barrio
 * Module:PC2
 */
public class CPCalculatorFrame extends javax.swing.JFrame {
    
    private CalculatorModel calModel;
    private int round = 9;

    /**
     * Creates new form CPCalculatorFrame
     */
    public CPCalculatorFrame() {
        
        initComponents();
        this.setSize(260, 335);
        this.panExtended.setVisible(false);
        calModel = new CalculatorModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrView = new javax.swing.ButtonGroup();
        bgrFont = new javax.swing.ButtonGroup();
        msgHotKeys = new javax.swing.JOptionPane();
        msgAbout = new javax.swing.JOptionPane();
        bgrRound = new javax.swing.ButtonGroup();
        bgrAngleConversion = new javax.swing.ButtonGroup();
        msgMessage = new javax.swing.JOptionPane();
        panBasic = new javax.swing.JPanel();
        lblDisplay = new javax.swing.JLabel();
        btn1overX = new javax.swing.JButton();
        btnNumber3 = new javax.swing.JButton();
        btnNumber2 = new javax.swing.JButton();
        btnDecimalPoint = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnNumber4 = new javax.swing.JButton();
        btnNumber1 = new javax.swing.JButton();
        btnNumber5 = new javax.swing.JButton();
        btnNumber6 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnExponent = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnNumber8 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnNumber7 = new javax.swing.JButton();
        btnNumber9 = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnClearEntry = new javax.swing.JButton();
        btnNumber0 = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        panExtended = new javax.swing.JPanel();
        btnASine = new javax.swing.JButton();
        btnATangent = new javax.swing.JButton();
        btnSine = new javax.swing.JButton();
        btnACosine = new javax.swing.JButton();
        btnCosine = new javax.swing.JButton();
        btnEuler = new javax.swing.JButton();
        btnTangent = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();
        radDegrees = new javax.swing.JRadioButton();
        radRadians = new javax.swing.JRadioButton();
        mnuMain = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        chkBasic = new javax.swing.JCheckBoxMenuItem();
        chkExtended = new javax.swing.JCheckBoxMenuItem();
        mnuFont = new javax.swing.JMenu();
        chkPlain = new javax.swing.JCheckBoxMenuItem();
        chkBold = new javax.swing.JCheckBoxMenuItem();
        mnuRound = new javax.swing.JMenu();
        chkRound0 = new javax.swing.JCheckBoxMenuItem();
        chkRound1 = new javax.swing.JCheckBoxMenuItem();
        chkRound2 = new javax.swing.JCheckBoxMenuItem();
        chkRound3 = new javax.swing.JCheckBoxMenuItem();
        chkRound4 = new javax.swing.JCheckBoxMenuItem();
        chkRound5 = new javax.swing.JCheckBoxMenuItem();
        chkRound6 = new javax.swing.JCheckBoxMenuItem();
        chkRound7 = new javax.swing.JCheckBoxMenuItem();
        chkRound8 = new javax.swing.JCheckBoxMenuItem();
        chkRound9 = new javax.swing.JCheckBoxMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuHotKeys = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CPCalculator");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 255));
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(345, 350));
        setMinimumSize(new java.awt.Dimension(260, 350));
        setPreferredSize(new java.awt.Dimension(345, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        panBasic.setToolTipText("");
        panBasic.setMaximumSize(new java.awt.Dimension(345, 340));
        panBasic.setMinimumSize(new java.awt.Dimension(345, 335));
        panBasic.setOpaque(false);
        panBasic.setPreferredSize(new java.awt.Dimension(345, 340));
        panBasic.setLayout(null);

        lblDisplay.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panBasic.add(lblDisplay);
        lblDisplay.setBounds(10, 10, 195, 30);

        btn1overX.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btn1overX.setText("1/x");
        btn1overX.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btn1overX.setMaximumSize(new java.awt.Dimension(40, 40));
        btn1overX.setMinimumSize(new java.awt.Dimension(40, 40));
        btn1overX.setPreferredSize(new java.awt.Dimension(40, 40));
        btn1overX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1overXActionPerformed(evt);
            }
        });
        panBasic.add(btn1overX);
        btn1overX.setBounds(170, 50, 38, 38);

        btnNumber3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber3.setText("3");
        btnNumber3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber3.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber3.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber3.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber3ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber3);
        btnNumber3.setBounds(90, 50, 38, 38);

        btnNumber2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber2.setText("2");
        btnNumber2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber2.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber2.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber2.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber2ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber2);
        btnNumber2.setBounds(50, 50, 38, 38);

        btnDecimalPoint.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnDecimalPoint.setText(".");
        btnDecimalPoint.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnDecimalPoint.setMaximumSize(new java.awt.Dimension(40, 40));
        btnDecimalPoint.setMinimumSize(new java.awt.Dimension(40, 40));
        btnDecimalPoint.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDecimalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalPointActionPerformed(evt);
            }
        });
        panBasic.add(btnDecimalPoint);
        btnDecimalPoint.setBounds(50, 200, 38, 38);

        btnMultiply.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnMultiply.setMaximumSize(new java.awt.Dimension(40, 40));
        btnMultiply.setMinimumSize(new java.awt.Dimension(40, 40));
        btnMultiply.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        panBasic.add(btnMultiply);
        btnMultiply.setBounds(130, 50, 38, 38);

        btnNumber4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber4.setText("4");
        btnNumber4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber4.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber4.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber4.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber4ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber4);
        btnNumber4.setBounds(10, 100, 38, 38);

        btnNumber1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber1.setText("1");
        btnNumber1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber1.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber1.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber1ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber1);
        btnNumber1.setBounds(10, 50, 38, 38);

        btnNumber5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber5.setText("5");
        btnNumber5.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber5.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber5.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber5.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber5ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber5);
        btnNumber5.setBounds(50, 100, 38, 38);

        btnNumber6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber6.setText("6");
        btnNumber6.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber6.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber6.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber6.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber6ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber6);
        btnNumber6.setBounds(90, 100, 38, 38);

        btnDivide.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnDivide.setMaximumSize(new java.awt.Dimension(40, 40));
        btnDivide.setMinimumSize(new java.awt.Dimension(40, 40));
        btnDivide.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        panBasic.add(btnDivide);
        btnDivide.setBounds(130, 100, 38, 38);

        btnExponent.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnExponent.setText("x^n");
        btnExponent.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnExponent.setMaximumSize(new java.awt.Dimension(40, 40));
        btnExponent.setMinimumSize(new java.awt.Dimension(40, 40));
        btnExponent.setPreferredSize(new java.awt.Dimension(40, 40));
        btnExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExponentActionPerformed(evt);
            }
        });
        panBasic.add(btnExponent);
        btnExponent.setBounds(170, 100, 38, 38);

        btnPlusMinus.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnPlusMinus.setText("+/-");
        btnPlusMinus.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnPlusMinus.setMaximumSize(new java.awt.Dimension(40, 40));
        btnPlusMinus.setMinimumSize(new java.awt.Dimension(40, 40));
        btnPlusMinus.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });
        panBasic.add(btnPlusMinus);
        btnPlusMinus.setBounds(170, 150, 38, 38);

        btnNumber8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber8.setText("8");
        btnNumber8.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber8.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber8.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber8.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber8ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber8);
        btnNumber8.setBounds(50, 150, 38, 38);

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnAdd.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAdd.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAdd.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panBasic.add(btnAdd);
        btnAdd.setBounds(130, 150, 38, 38);

        btnNumber7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber7.setText("7");
        btnNumber7.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber7.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber7.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber7.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber7ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber7);
        btnNumber7.setBounds(10, 150, 38, 38);

        btnNumber9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber9.setText("9");
        btnNumber9.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber9.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber9.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber9.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber9ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber9);
        btnNumber9.setBounds(90, 150, 38, 38);

        btnEquals.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnEquals.setText("=");
        btnEquals.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnEquals.setMaximumSize(new java.awt.Dimension(40, 40));
        btnEquals.setMinimumSize(new java.awt.Dimension(40, 40));
        btnEquals.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        panBasic.add(btnEquals);
        btnEquals.setBounds(90, 200, 38, 38);

        btnMinus.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnMinus.setText("-");
        btnMinus.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnMinus.setMaximumSize(new java.awt.Dimension(40, 40));
        btnMinus.setMinimumSize(new java.awt.Dimension(40, 40));
        btnMinus.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        panBasic.add(btnMinus);
        btnMinus.setBounds(130, 200, 38, 38);

        btnFactorial.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnFactorial.setText("x!");
        btnFactorial.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnFactorial.setMaximumSize(new java.awt.Dimension(40, 40));
        btnFactorial.setMinimumSize(new java.awt.Dimension(40, 40));
        btnFactorial.setPreferredSize(new java.awt.Dimension(40, 40));
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        panBasic.add(btnFactorial);
        btnFactorial.setBounds(170, 200, 38, 38);

        btnClearEntry.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnClearEntry.setText("CE");
        btnClearEntry.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnClearEntry.setMaximumSize(new java.awt.Dimension(40, 90));
        btnClearEntry.setMinimumSize(new java.awt.Dimension(40, 90));
        btnClearEntry.setPreferredSize(new java.awt.Dimension(40, 90));
        btnClearEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEntryActionPerformed(evt);
            }
        });
        panBasic.add(btnClearEntry);
        btnClearEntry.setBounds(90, 250, 76, 38);

        btnNumber0.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnNumber0.setText("0");
        btnNumber0.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNumber0.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNumber0.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNumber0.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber0ActionPerformed(evt);
            }
        });
        panBasic.add(btnNumber0);
        btnNumber0.setBounds(10, 200, 38, 38);

        btnClearAll.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnClearAll.setText("CA");
        btnClearAll.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnClearAll.setMaximumSize(new java.awt.Dimension(40, 90));
        btnClearAll.setMinimumSize(new java.awt.Dimension(40, 90));
        btnClearAll.setPreferredSize(new java.awt.Dimension(40, 90));
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });
        panBasic.add(btnClearAll);
        btnClearAll.setBounds(10, 250, 76, 38);

        getContentPane().add(panBasic);
        panBasic.setBounds(0, 0, 210, 290);

        panExtended.setLayout(null);

        btnASine.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnASine.setText("asin");
        btnASine.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnASine.setMaximumSize(new java.awt.Dimension(40, 40));
        btnASine.setMinimumSize(new java.awt.Dimension(40, 40));
        btnASine.setPreferredSize(new java.awt.Dimension(40, 40));
        btnASine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASineActionPerformed(evt);
            }
        });
        panExtended.add(btnASine);
        btnASine.setBounds(50, 50, 38, 38);

        btnATangent.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnATangent.setText("atan");
        btnATangent.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnATangent.setMaximumSize(new java.awt.Dimension(40, 40));
        btnATangent.setMinimumSize(new java.awt.Dimension(40, 40));
        btnATangent.setPreferredSize(new java.awt.Dimension(40, 40));
        btnATangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATangentActionPerformed(evt);
            }
        });
        panExtended.add(btnATangent);
        btnATangent.setBounds(50, 150, 38, 38);

        btnSine.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnSine.setText("sin");
        btnSine.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnSine.setMaximumSize(new java.awt.Dimension(40, 40));
        btnSine.setMinimumSize(new java.awt.Dimension(40, 40));
        btnSine.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSineActionPerformed(evt);
            }
        });
        panExtended.add(btnSine);
        btnSine.setBounds(5, 50, 38, 38);

        btnACosine.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnACosine.setText("acos");
        btnACosine.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnACosine.setMaximumSize(new java.awt.Dimension(40, 40));
        btnACosine.setMinimumSize(new java.awt.Dimension(40, 40));
        btnACosine.setPreferredSize(new java.awt.Dimension(40, 40));
        btnACosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACosineActionPerformed(evt);
            }
        });
        panExtended.add(btnACosine);
        btnACosine.setBounds(50, 100, 38, 38);

        btnCosine.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnCosine.setText("cos");
        btnCosine.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnCosine.setMaximumSize(new java.awt.Dimension(40, 40));
        btnCosine.setMinimumSize(new java.awt.Dimension(40, 40));
        btnCosine.setPreferredSize(new java.awt.Dimension(40, 40));
        btnCosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosineActionPerformed(evt);
            }
        });
        panExtended.add(btnCosine);
        btnCosine.setBounds(5, 100, 38, 38);

        btnEuler.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnEuler.setText("E");
        btnEuler.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnEuler.setMaximumSize(new java.awt.Dimension(40, 40));
        btnEuler.setMinimumSize(new java.awt.Dimension(40, 40));
        btnEuler.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEulerActionPerformed(evt);
            }
        });
        panExtended.add(btnEuler);
        btnEuler.setBounds(50, 200, 38, 38);

        btnTangent.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnTangent.setText("tan");
        btnTangent.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnTangent.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTangent.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTangent.setPreferredSize(new java.awt.Dimension(40, 40));
        btnTangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangentActionPerformed(evt);
            }
        });
        panExtended.add(btnTangent);
        btnTangent.setBounds(5, 150, 38, 38);

        btnPI.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnPI.setText("Pi");
        btnPI.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnPI.setMaximumSize(new java.awt.Dimension(40, 40));
        btnPI.setMinimumSize(new java.awt.Dimension(40, 40));
        btnPI.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });
        panExtended.add(btnPI);
        btnPI.setBounds(5, 200, 38, 38);

        bgrAngleConversion.add(radDegrees);
        radDegrees.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radDegrees.setText("Degrees");
        radDegrees.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDegreesItemStateChanged(evt);
            }
        });
        radDegrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDegreesActionPerformed(evt);
            }
        });
        panExtended.add(radDegrees);
        radDegrees.setBounds(0, 0, 100, 25);

        bgrAngleConversion.add(radRadians);
        radRadians.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radRadians.setText("Radians");
        radRadians.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radRadiansItemStateChanged(evt);
            }
        });
        radRadians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRadiansActionPerformed(evt);
            }
        });
        panExtended.add(radRadians);
        radRadians.setBounds(0, 20, 110, 25);

        getContentPane().add(panExtended);
        panExtended.setBounds(210, 0, 100, 290);

        mnuView.setText("View");

        bgrView.add(chkBasic);
        chkBasic.setSelected(true);
        chkBasic.setText("Basic");
        chkBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBasicActionPerformed(evt);
            }
        });
        mnuView.add(chkBasic);

        bgrView.add(chkExtended);
        chkExtended.setText("Extended");
        chkExtended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExtendedActionPerformed(evt);
            }
        });
        mnuView.add(chkExtended);

        mnuMain.add(mnuView);

        mnuFont.setText("Font");

        bgrFont.add(chkPlain);
        chkPlain.setSelected(true);
        chkPlain.setText("Plain");
        chkPlain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPlainItemStateChanged(evt);
            }
        });
        chkPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPlainActionPerformed(evt);
            }
        });
        mnuFont.add(chkPlain);

        bgrFont.add(chkBold);
        chkBold.setText("Bold");
        chkBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBoldItemStateChanged(evt);
            }
        });
        mnuFont.add(chkBold);

        mnuMain.add(mnuFont);

        mnuRound.setText("Round");

        bgrRound.add(chkRound0);
        chkRound0.setText("0");
        chkRound0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkRound0ItemStateChanged(evt);
            }
        });
        chkRound0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound0ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound0);

        bgrRound.add(chkRound1);
        chkRound1.setText("1");
        chkRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound1ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound1);

        bgrRound.add(chkRound2);
        chkRound2.setText("2");
        chkRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound2ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound2);

        bgrRound.add(chkRound3);
        chkRound3.setText("3");
        chkRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound3ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound3);

        bgrRound.add(chkRound4);
        chkRound4.setText("4");
        chkRound4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound4ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound4);

        bgrRound.add(chkRound5);
        chkRound5.setText("5");
        chkRound5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound5ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound5);

        bgrRound.add(chkRound6);
        chkRound6.setText("6");
        chkRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound6ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound6);

        bgrRound.add(chkRound7);
        chkRound7.setText("7");
        chkRound7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound7ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound7);

        bgrRound.add(chkRound8);
        chkRound8.setText("8");
        chkRound8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound8ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound8);

        bgrRound.add(chkRound9);
        chkRound9.setSelected(true);
        chkRound9.setText("9");
        chkRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRound9ActionPerformed(evt);
            }
        });
        mnuRound.add(chkRound9);

        mnuMain.add(mnuRound);

        mnuHelp.setText("Help");

        mnuHotKeys.setText("Hot keys");
        mnuHotKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHotKeysActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHotKeys);

        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        mnuMain.add(mnuHelp);

        setJMenuBar(mnuMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnDecimalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalPointActionPerformed
        if (lblDisplay.getText().contains(this.btnDecimalPoint.getText()) && !calModel.isPrevCalc()) {
            //do nothing
        } else{
            updateDisplay(".");
        }
    }//GEN-LAST:event_btnDecimalPointActionPerformed

    private void btnNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber8ActionPerformed
        updateDisplay("8");
    }//GEN-LAST:event_btnNumber8ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        findOperator(1); //add        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber7ActionPerformed
        updateDisplay("7");
    }//GEN-LAST:event_btnNumber7ActionPerformed

    private void btnNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber9ActionPerformed
        updateDisplay("9");
    }//GEN-LAST:event_btnNumber9ActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        findOperator(16);//equals
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        findOperator(2);//subtract
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        findOperator(9);//factorial
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnClearEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEntryActionPerformed
        lblDisplay.setText("");
    }//GEN-LAST:event_btnClearEntryActionPerformed

    private void btnNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber0ActionPerformed
        updateDisplay("0");
    }//GEN-LAST:event_btnNumber0ActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        lblDisplay.setText("");
        calModel.setNum1(0);
        calModel.setOperator(0);
        calModel.setNum1Set(false);
        calModel.setOperatorSet(false);
        calModel.setPrevCalc(false);
        lblDisplay.setText("");       
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void btn1overXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1overXActionPerformed
        findOperator(8); //reciprocal
    }//GEN-LAST:event_btn1overXActionPerformed

    private void btnCosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosineActionPerformed
        findOperator(11);//cos
    }//GEN-LAST:event_btnCosineActionPerformed

    private void chkPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPlainActionPerformed

    }//GEN-LAST:event_chkPlainActionPerformed

    private void chkBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBasicActionPerformed
        if (panExtended.isVisible()) {
            panBasic.setVisible(true);
            panExtended.setVisible(false);
            this.setSize(260, 335);
            
        }

    }//GEN-LAST:event_chkBasicActionPerformed

    private void chkExtendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExtendedActionPerformed
        if (!panExtended.isVisible()) {
            panBasic.setVisible(true);
            panExtended.setVisible(true);
            this.setSize(320, 335);
            
        }
    }//GEN-LAST:event_chkExtendedActionPerformed

    private void chkPlainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPlainItemStateChanged
        if (chkPlain.isSelected()) {
            java.awt.Font oldFont = this.getFont();
            java.awt.Font newFont = new java.awt.Font(oldFont.getName(), java.awt.Font.PLAIN, oldFont.getSize());
            
            btn1overX.setFont(newFont);
            btnACosine.setFont(newFont);
            btnASine.setFont(newFont);
            btnATangent.setFont(newFont);
            btnAdd.setFont(newFont);
            btnClearAll.setFont(newFont);
            btnClearEntry.setFont(newFont);
            btnCosine.setFont(newFont);
            btnDecimalPoint.setFont(newFont);
            btnDivide.setFont(newFont);
            btnEquals.setFont(newFont);
            btnEuler.setFont(newFont);
            btnExponent.setFont(newFont);
            btnFactorial.setFont(newFont);
            btnMinus.setFont(newFont);
            btnMultiply.setFont(newFont);
            btnNumber0.setFont(newFont);
            btnNumber1.setFont(newFont);
            btnNumber2.setFont(newFont);
            btnNumber3.setFont(newFont);
            btnNumber4.setFont(newFont);
            btnNumber5.setFont(newFont);
            btnNumber6.setFont(newFont);
            btnNumber7.setFont(newFont);
            btnNumber8.setFont(newFont);
            btnNumber9.setFont(newFont);
            btnPI.setFont(newFont);
            btnPlusMinus.setFont(newFont);
            btnSine.setFont(newFont);
            btnTangent.setFont(newFont);
            chkBasic.setFont(newFont);
            chkBold.setFont(newFont);
            chkExtended.setFont(newFont);
            chkPlain.setFont(newFont);
            chkRound0.setFont(newFont);
            chkRound1.setFont(newFont);
            chkRound2.setFont(newFont);
            chkRound3.setFont(newFont);
            chkRound4.setFont(newFont);
            chkRound5.setFont(newFont);
            chkRound6.setFont(newFont);
            chkRound7.setFont(newFont);
            chkRound8.setFont(newFont);
            chkRound9.setFont(newFont);
            lblDisplay.setFont(newFont);
            mnuAbout.setFont(newFont);
            msgHotKeys.setFont(newFont);
            mnuFont.setFont(newFont);
            mnuHelp.setFont(newFont);
            mnuHotKeys.setFont(newFont);
            mnuMain.setFont(newFont);
            mnuRound.setFont(newFont);
            mnuView.setFont(newFont);
            msgHotKeys.setFont(newFont);
            panBasic.setFont(newFont);
            panExtended.setFont(newFont);
            radDegrees.setFont(newFont);
            radRadians.setFont(newFont);
        }
    }//GEN-LAST:event_chkPlainItemStateChanged

    private void chkBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBoldItemStateChanged
        if (chkBold.isSelected()) {
            java.awt.Font oldFont = this.getFont();
            java.awt.Font newFont = new java.awt.Font(oldFont.getName(), java.awt.Font.BOLD, oldFont.getSize());
            btn1overX.setFont(newFont);
            btnACosine.setFont(newFont);
            btnASine.setFont(newFont);
            btnATangent.setFont(newFont);
            btnAdd.setFont(newFont);
            btnClearAll.setFont(newFont);
            btnClearEntry.setFont(newFont);
            btnCosine.setFont(newFont);
            btnDecimalPoint.setFont(newFont);
            btnDivide.setFont(newFont);
            btnEquals.setFont(newFont);
            btnEuler.setFont(newFont);
            btnExponent.setFont(newFont);
            btnFactorial.setFont(newFont);
            btnMinus.setFont(newFont);
            btnMultiply.setFont(newFont);
            btnNumber0.setFont(newFont);
            btnNumber1.setFont(newFont);
            btnNumber2.setFont(newFont);
            btnNumber3.setFont(newFont);
            btnNumber4.setFont(newFont);
            btnNumber5.setFont(newFont);
            btnNumber6.setFont(newFont);
            btnNumber7.setFont(newFont);
            btnNumber8.setFont(newFont);
            btnNumber9.setFont(newFont);
            btnPI.setFont(newFont);
            btnPlusMinus.setFont(newFont);
            btnSine.setFont(newFont);
            btnTangent.setFont(newFont);
            chkBasic.setFont(newFont);
            chkBold.setFont(newFont);
            chkExtended.setFont(newFont);
            chkPlain.setFont(newFont);
            chkRound0.setFont(newFont);
            chkRound1.setFont(newFont);
            chkRound2.setFont(newFont);
            chkRound3.setFont(newFont);
            chkRound4.setFont(newFont);
            chkRound5.setFont(newFont);
            chkRound6.setFont(newFont);
            chkRound7.setFont(newFont);
            chkRound8.setFont(newFont);
            chkRound9.setFont(newFont);
            lblDisplay.setFont(newFont);
            mnuAbout.setFont(newFont);
            msgHotKeys.setFont(newFont);
            mnuFont.setFont(newFont);
            mnuHelp.setFont(newFont);
            mnuHotKeys.setFont(newFont);
            mnuMain.setFont(newFont);
            mnuRound.setFont(newFont);
            mnuView.setFont(newFont);
            msgHotKeys.setFont(newFont);
            panBasic.setFont(newFont);
            panExtended.setFont(newFont);
            radDegrees.setFont(newFont);
            radRadians.setFont(newFont);
        }
    }//GEN-LAST:event_chkBoldItemStateChanged

    private void mnuHotKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHotKeysActionPerformed
        msgHotKeys.showMessageDialog(this, "+    addition\n-     subtraction\n*     multiplication\n/     division\n\n"
                + "s     sin\nS     arcsin\nc     cos\nC     arcCos\n"
                + "t      tan\nT     arctan\n\n"
                + "i      inverse\nm     +/-\n^     power\n!     factorial\n\n"
                + "d     clearall(CA)\nD     clear entry(CE)\n\nDigits 0-9 can be entered from the\nkeypad or the keyboards's digit keys.\n", "Hot Keys", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHotKeysActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        msgHotKeys.showMessageDialog(this, "CpCalculator\nVersion1.2.3_456\nOctober 2014\n\nCreated by MJ del Barrio\nStudent Number: 91023487", null, WIDTH);
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void btnNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber1ActionPerformed
        updateDisplay("1");
    }//GEN-LAST:event_btnNumber1ActionPerformed

    private void btnNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber2ActionPerformed
        updateDisplay("2");
    }//GEN-LAST:event_btnNumber2ActionPerformed

    private void btnNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber3ActionPerformed
        updateDisplay("3");
    }//GEN-LAST:event_btnNumber3ActionPerformed

    private void btnNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber4ActionPerformed
        updateDisplay("4");
    }//GEN-LAST:event_btnNumber4ActionPerformed

    private void btnNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber5ActionPerformed
        updateDisplay("5");
    }//GEN-LAST:event_btnNumber5ActionPerformed

    private void btnNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber6ActionPerformed
        updateDisplay("6");
    }//GEN-LAST:event_btnNumber6ActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        findOperator(3); //multiply
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        findOperator(4);// divide
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEulerActionPerformed
        lblDisplay.setText(String.valueOf(Math.E));
    }//GEN-LAST:event_btnEulerActionPerformed

    private void radDegreesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDegreesItemStateChanged

    }//GEN-LAST:event_radDegreesItemStateChanged

    private void btnSineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSineActionPerformed
        findOperator(10);// sine
    }//GEN-LAST:event_btnSineActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        lblDisplay.setText(String.valueOf(Double.parseDouble(lblDisplay.getText()) * (-1)));
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnTangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangentActionPerformed
        findOperator(12);//tan
    }//GEN-LAST:event_btnTangentActionPerformed

    private void radRadiansItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radRadiansItemStateChanged
        this.radRadians.isSelected();
    }//GEN-LAST:event_radRadiansItemStateChanged

    private void btnExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponentActionPerformed
        findOperator(5);//exponent
    }//GEN-LAST:event_btnExponentActionPerformed

    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
        lblDisplay.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_btnPIActionPerformed

    private void btnASineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASineActionPerformed
        findOperator(13);//asin
    }//GEN-LAST:event_btnASineActionPerformed

    private void btnACosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACosineActionPerformed
        findOperator(14);//acos
    }//GEN-LAST:event_btnACosineActionPerformed

    private void btnATangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATangentActionPerformed
        findOperator(15);//atan
    }//GEN-LAST:event_btnATangentActionPerformed

    private void chkRound0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkRound0ItemStateChanged
        round = 0;
    }//GEN-LAST:event_chkRound0ItemStateChanged

    private void chkRound0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound0ActionPerformed
        round = 0;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound0ActionPerformed

    private void chkRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound1ActionPerformed
        round = 1;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound1ActionPerformed

    private void chkRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound2ActionPerformed
        round = 2;        
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound2ActionPerformed

    private void chkRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound3ActionPerformed
        round = 3;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound3ActionPerformed

    private void chkRound4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound4ActionPerformed
        round = 4;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound4ActionPerformed

    private void chkRound5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound5ActionPerformed
        round = 5;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound5ActionPerformed

    private void chkRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound6ActionPerformed
        round = 6;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound6ActionPerformed

    private void chkRound7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound7ActionPerformed
        round = 7;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound7ActionPerformed

    private void chkRound8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound8ActionPerformed
        round = 8;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound8ActionPerformed

    private void chkRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRound9ActionPerformed
        round = 9;
        this.checkRoundingPrecision();
    }//GEN-LAST:event_chkRound9ActionPerformed

    private void radDegreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDegreesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radDegreesActionPerformed

    private void radRadiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRadiansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radRadiansActionPerformed
    
    public void checkRoundingPrecision() {
        DecimalFormat df = new DecimalFormat("##.###");
        df.setMaximumFractionDigits(round);
        df.setMinimumFractionDigits(round);
        if (calModel.isNum1Set()) {
            // this.radiansOrDegrees();
            lblDisplay.setText(String.valueOf(df.format(calModel.getNum1())));             
        } else {
            lblDisplay.setText((df.format(Double.parseDouble(lblDisplay.getText()))));            
        }       
    }

    private void radiansOrDegrees() {
        if (this.radDegrees.isSelected()) {
            calModel.setDegreesSet(true);
            calModel.setRadianSet(false);
            
        } else if (this.radRadians.isSelected()) {
            calModel.setDegreesSet(false);
            calModel.setRadianSet(true);            
        }
    }
    
    public void updateDisplay(String keyPressed) {        
        if (calModel.isPrevCalc()) {
            lblDisplay.setText("");
            calModel.setPrevCalc(false);
        } else {
            //do nothing
        }
        lblDisplay.setText(lblDisplay.getText() + keyPressed);        
    }
    
    public void findOperator(int operator) {
        this.radiansOrDegrees();
        calModel.setInputNumber(Double.parseDouble(lblDisplay.getText())); 
        calModel.setInputOperator(operator);
          try {
        calModel.determineOperator();       
          } catch (Exception e){
            msgMessage.showMessageDialog(this, e.getMessage(),"ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
              calModel.setPrevCalc(false);
              calModel.setNum1(0);
              calModel.setNum1Set(false);
              calModel.setNum2(0);              
          }
        if (calModel.isPrevCalc()) {
            //lblDisplay.setText(String.valueOf(calModel.getNum1()));
            this.checkRoundingPrecision();                      
        } else {
            lblDisplay.setText("");            
        }        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrAngleConversion;
    private javax.swing.ButtonGroup bgrFont;
    private javax.swing.ButtonGroup bgrRound;
    private javax.swing.ButtonGroup bgrView;
    private javax.swing.JButton btn1overX;
    private javax.swing.JButton btnACosine;
    private javax.swing.JButton btnASine;
    private javax.swing.JButton btnATangent;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnClearEntry;
    private javax.swing.JButton btnCosine;
    private javax.swing.JButton btnDecimalPoint;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnEuler;
    private javax.swing.JButton btnExponent;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNumber0;
    private javax.swing.JButton btnNumber1;
    private javax.swing.JButton btnNumber2;
    private javax.swing.JButton btnNumber3;
    private javax.swing.JButton btnNumber4;
    private javax.swing.JButton btnNumber5;
    private javax.swing.JButton btnNumber6;
    private javax.swing.JButton btnNumber7;
    private javax.swing.JButton btnNumber8;
    private javax.swing.JButton btnNumber9;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSine;
    private javax.swing.JButton btnTangent;
    private javax.swing.JCheckBoxMenuItem chkBasic;
    private javax.swing.JCheckBoxMenuItem chkBold;
    private javax.swing.JCheckBoxMenuItem chkExtended;
    private javax.swing.JCheckBoxMenuItem chkPlain;
    private javax.swing.JCheckBoxMenuItem chkRound0;
    private javax.swing.JCheckBoxMenuItem chkRound1;
    private javax.swing.JCheckBoxMenuItem chkRound2;
    private javax.swing.JCheckBoxMenuItem chkRound3;
    private javax.swing.JCheckBoxMenuItem chkRound4;
    private javax.swing.JCheckBoxMenuItem chkRound5;
    private javax.swing.JCheckBoxMenuItem chkRound6;
    private javax.swing.JCheckBoxMenuItem chkRound7;
    private javax.swing.JCheckBoxMenuItem chkRound8;
    private javax.swing.JCheckBoxMenuItem chkRound9;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHotKeys;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JMenu mnuView;
    private javax.swing.JOptionPane msgAbout;
    private javax.swing.JOptionPane msgHotKeys;
    private javax.swing.JOptionPane msgMessage;
    private javax.swing.JPanel panBasic;
    private javax.swing.JPanel panExtended;
    private javax.swing.JRadioButton radDegrees;
    private javax.swing.JRadioButton radRadians;
    // End of variables declaration//GEN-END:variables
}
